### ISSUE TITLE
ReadProm() incorrectly reads the coefficients and Calc_CRC4() returns zeros

### ISSUE THREAD

**Issue by vatlark** [Schm1tz1/arduino-ms5xxx#1]
The setup: I'm working with an arduino pro mini(using the arduino bootloader) and a MS5607 barometer.

The Problem: ReadCalc was returning the wrong result (which I only knew because I fixed Calc_CRC4)
The Solution: replace "char c" with " unsigned int c"
## The working code*:

void MS5xxx::ReadProm() {
    send_cmd(MS5xxx_CMD_RESET);
    delay(3);

```
for(uint8_t i=0;i<8;i++) 
{
    C[i]=0x0000;
    send_cmd(MS5xxx_CMD_PROM_RD+2*i);
    _Wire->requestFrom(i2caddr, 2);

    unsigned int c = _Wire->read();
    C[i] = (c << 8);
    c = _Wire->read();
    C[i] += c;
    _Wire->endTransmission(true);
}
```
## }

The Second Problem: Calc_CRC4 was returning zero.
The Second Solution: I adapted the "crc4" function from document AN520 by measurement specialties
## The working code*:

unsigned char MS5xxx::Calc_CRC4()
{
 int cnt; // simple counter
 unsigned int n_rem; // crc reminder
 unsigned int crc_read; // original value of the crc
 unsigned char n_bit;
 n_rem = 0x00;
 crc_read=C[7]; //save read CRC
 C[7]=(0xFF00 & (C[7])); //CRC byte is replaced by 0
 for (cnt = 0; cnt < 16; cnt++) // operation is performed on bytes
 {// choose LSB or MSB
if (cnt%2==1) n_rem ^= (unsigned short) ((C[cnt>>1]) & 0x00FF);
 else n_rem ^= (unsigned short) (C[cnt>>1]>>8);
 for (n_bit = 8; n_bit > 0; n_bit--)
 {
 if (n_rem & (0x8000))
 {
 n_rem = (n_rem << 1) ^ 0x3000; 
 }
 else
 {
 n_rem = (n_rem << 1);
 }
 }
 }
 n_rem= (0x000F & (n_rem >> 12)); // final 4-bit reminder is CRC code
 C[7]=crc_read; // restore the crc_read to its original place
 return (n_rem ^ 0x0);
## To test the code, per AN520, I added this function*:

unsigned char MS5xxx::CRCcodeTest(){
  unsigned int nprom[] = {0x3132,0x3334,0x3536,0x3738,0x3940,0x4142,0x4344,0x4500}; //expected output is 0xB
  for(uint8_t i=0;i<8;i++) 
    {
    C[i] = nprom[i];
  }
  unsigned char crc = Calc_CRC4(); //expected output is 0xB
  ReadProm();
  return crc;
## }

*note: after substituting in these new functions you will need to update the header appropriatly

**Comment by vatlark** [comment]
sorry for the weird formatting. It wasn't intentional

**Comment by Schm1tz1** [comment]
Hi, thanks a lot for your contribution. I never actually used the CRC, it's great to see it is really working. During my first tests a colleague pointed out that it doesn't match but due to lack of time we never really debugged the CRC-part. Cross-checks with other sensors showed that we meet out accuracy requirements so for our purpose it was more than good enough anyway. I will try to get a module and do some checks with your code. You can do a pull-request with your changes if you like, I'd be happy to add your bug-fix to this repo.
